// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeHs_q4YZqHa0gVaEdCTfiR_NwK_MQUZg',
    appId: '1:141826416177:web:15428e4b003f40100c3f10',
    messagingSenderId: '141826416177',
    projectId: 'inventrack-pgascom-f60a9',
    authDomain: 'inventrack-pgascom-f60a9.firebaseapp.com',
    storageBucket: 'inventrack-pgascom-f60a9.firebasestorage.app',
    measurementId: 'G-MMF91NS03J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0D_mCjHk2Dd8O8OnRpR7arm4fZ6bL7uo',
    appId: '1:141826416177:android:ebc5ef8ceeac8b300c3f10',
    messagingSenderId: '141826416177',
    projectId: 'inventrack-pgascom-f60a9',
    storageBucket: 'inventrack-pgascom-f60a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnx3T4n5pZMsXxOISA-JYiACFZpYHQkPE',
    appId: '1:141826416177:ios:afd0a499076006c80c3f10',
    messagingSenderId: '141826416177',
    projectId: 'inventrack-pgascom-f60a9',
    storageBucket: 'inventrack-pgascom-f60a9.firebasestorage.app',
    iosBundleId: 'com.example.inventrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnx3T4n5pZMsXxOISA-JYiACFZpYHQkPE',
    appId: '1:141826416177:ios:afd0a499076006c80c3f10',
    messagingSenderId: '141826416177',
    projectId: 'inventrack-pgascom-f60a9',
    storageBucket: 'inventrack-pgascom-f60a9.firebasestorage.app',
    iosBundleId: 'com.example.inventrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeHs_q4YZqHa0gVaEdCTfiR_NwK_MQUZg',
    appId: '1:141826416177:web:0a13eff8a82da7f70c3f10',
    messagingSenderId: '141826416177',
    projectId: 'inventrack-pgascom-f60a9',
    authDomain: 'inventrack-pgascom-f60a9.firebaseapp.com',
    storageBucket: 'inventrack-pgascom-f60a9.firebasestorage.app',
    measurementId: 'G-0DX7D719G7',
  );
}
